global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  # Prometheus 本身
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Rate Limiter Control Plane
  - job_name: 'limiter-control-plane'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']  # Docker 内访问宿主机
    scrape_interval: 10s
    scrape_timeout: 5s

  # Rate Limiter Data Plane
  - job_name: 'limiter-data-plane'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
    scrape_interval: 5s   # Data Plane 更频繁采集
    scrape_timeout: 5s

  # Rate Limiter Accounting
  - job_name: 'limiter-accounting'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
    scrape_interval: 10s
    scrape_timeout:  5s